// // // export const PROFESSIONALS = [
// // //   {
// // //     "id": "p1",
// // //     "name": "אילן כהן",
// // //     "category": "Tutors and Private Teachers",
// // //     "rating": 4.9,
// // //     "pricePerHour": 150,
// // //     "city": "Tel Aviv",
// // //     "distanceKm": 2.1,
// // //     "availableNow": true,
// // //     "reviews": 112,
// // //     "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80&auto=format&fit=crop",
// // //     "bio": "מורה פרטי במתמטיקה עם ניסיון של 10 שנים."
// // //   },
// // //   {
// // //     "id": "p2",
// // //     "name": "שרה גולדברג",
// // //     "category": "Law, Finance, and Management",
// // //     "rating": 4.7,
// // //     "pricePerHour": 300,
// // //     "city": "Jerusalem",
// // //     "distanceKm": 48,
// // //     "availableNow": false,
// // //     "reviews": 45,
// // //     "avatar": "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=800&q=80&auto=format&fit=crop",
// // //     "bio": "ייעוץ משפטי לעסקים קטנים."
// // //   },
// // //   {
// // //     "id": "p3",
// // //     "name": "Pro 3",
// // //     "category": "Coaches and Veterinarians",
// // //     "rating": 4.06,
// // //     "pricePerHour": 80,
// // //     "city": "Netanya",
// // //     "distanceKm": 46.4,
// // //     "availableNow": false,
// // //     "reviews": 48,
// // //     "avatar": "https://images.unsplash.com/photo-1599566150163-29194dcaad36?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&fm=jpg&q=60&w=3000",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p4",
// // //     "name": "פרופסי 4",
// // //     "category": "Services, Hospitality, and Sales",
// // //     "rating": 4.62,
// // //     "pricePerHour": 120,
// // //     "city": "Netanya",
// // //     "distanceKm": 42.0,
// // //     "availableNow": false,
// // //     "reviews": 136,
// // //     "avatar": "/avatars/avatar5.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p5",
// // //     "name": "Pro 5",
// // //     "category": "Law, Finance, and Management",
// // //     "rating": 3.85,
// // //     "pricePerHour": 400,
// // //     "city": "Netanya",
// // //     "distanceKm": 8.6,
// // //     "availableNow": true,
// // //     "reviews": 158,
// // //     "avatar": "/avatars/avatar6.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p6",
// // //     "name": "פרופסי 6",
// // //     "category": "Cleaning and Maintenance",
// // //     "rating": 4.71,
// // //     "pricePerHour": 250,
// // //     "city": "Tel Aviv",
// // //     "distanceKm": 12.1,
// // //     "availableNow": true,
// // //     "reviews": 47,
// // //     "avatar": "/avatars/avatar7.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p7",
// // //     "name": "Pro 7",
// // //     "category": "Law, Finance, and Management",
// // //     "rating": 3.73,
// // //     "pricePerHour": 250,
// // //     "city": "Netanya",
// // //     "distanceKm": 34.2,
// // //     "availableNow": false,
// // //     "reviews": 111,
// // //     "avatar": "/avatars/avatar8.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p8",
// // //     "name": "פרופסי 8",
// // //     "category": "Construction, Crafts, and Industry",
// // //     "rating": 4.52,
// // //     "pricePerHour": 250,
// // //     "city": "Haifa",
// // //     "distanceKm": 10.0,
// // //     "availableNow": false,
// // //     "reviews": 63,
// // //     "avatar": "/avatars/avatar9.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
    
// // //   },
// // //   {
// // //     "id": "p9",
// // //     "name": "Pro 9",
// // //     "category": "Tutors and Private Teachers",
// // //     "rating": 3.64,
// // //     "pricePerHour": 300,
// // //     "city": "Jerusalem",
// // //     "distanceKm": 33.4,
// // //     "availableNow": false,
// // //     "reviews": 146,
// // //     "avatar": "/avatars/avatar10.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p10",
// // //     "name": "פרופסי 10",
// // //     "category": "Services, Hospitality, and Sales",
// // //     "rating": 4.86,
// // //     "pricePerHour": 120,
// // //     "city": "Netanya",
// // //     "distanceKm": 28.9,
// // //     "availableNow": false,
// // //     "reviews": 94,
// // //     "avatar": "/avatars/avatar1.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p11",
// // //     "name": "Pro 11",
// // //     "category": "Construction, Crafts, and Industry",
// // //     "rating": 4.85,
// // //     "pricePerHour": 150,
// // //     "city": "Raanana",
// // //     "distanceKm": 45.3,
// // //     "availableNow": false,
// // //     "reviews": 85,
// // //     "avatar": "/avatars/avatar2.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p12",
// // //     "name": "פרופסי 12",
// // //     "category": "Construction, Crafts, and Industry",
// // //     "rating": 4.87,
// // //     "pricePerHour": 200,
// // //     "city": "Tel Aviv",
// // //     "distanceKm": 44.2,
// // //     "availableNow": false,
// // //     "reviews": 222,
// // //     "avatar": "/avatars/avatar3.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p13",
// // //     "name": "Pro 13",
// // //     "category": "Law, Finance, and Management",
// // //     "rating": 3.96,
// // //     "pricePerHour": 300,
// // //     "city": "Tel Aviv",
// // //     "distanceKm": 37.1,
// // //     "availableNow": false,
// // //     "reviews": 203,
// // //     "avatar": "/avatars/avatar4.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p14",
// // //     "name": "פרופסי 14",
// // //     "category": "Tutors and Private Teachers",
// // //     "rating": 4.63,
// // //     "pricePerHour": 120,
// // //     "city": "Tel Aviv",
// // //     "distanceKm": 31.7,
// // //     "availableNow": false,
// // //     "reviews": 153,
// // //     "avatar": "/avatars/avatar5.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p15",
// // //     "name": "Pro 15",
// // //     "category": "Coaches and Veterinarians",
// // //     "rating": 4.18,
// // //     "pricePerHour": 300,
// // //     "city": "Raanana",
// // //     "distanceKm": 23.2,
// // //     "availableNow": false,
// // //     "reviews": 206,
// // //     "avatar": "/avatars/avatar6.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p16",
// // //     "name": "פרופסי 16",
// // //     "category": "Law, Finance, and Management",
// // //     "rating": 4.5,
// // //     "pricePerHour": 300,
// // //     "city": "Tel Aviv",
// // //     "distanceKm": 10.7,
// // //     "availableNow": false,
// // //     "reviews": 203,
// // //     "avatar": "/avatars/avatar7.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p17",
// // //     "name": "Pro 17",
// // //     "category": "Cleaning and Maintenance",
// // //     "rating": 3.94,
// // //     "pricePerHour": 200,
// // //     "city": "Jerusalem",
// // //     "distanceKm": 3.8,
// // //     "availableNow": false,
// // //     "reviews": 131,
// // //     "avatar": "/avatars/avatar8.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p18",
// // //     "name": "פרופסי 18",
// // //     "category": "Cleaning and Maintenance",
// // //     "rating": 3.72,
// // //     "pricePerHour": 300,
// // //     "city": "Haifa",
// // //     "distanceKm": 0.6,
// // //     "availableNow": false,
// // //     "reviews": 5,
// // //     "avatar": "/avatars/avatar9.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p19",
// // //     "name": "Pro 19",
// // //     "category": "Services, Hospitality, and Sales",
// // //     "rating": 4.65,
// // //     "pricePerHour": 200,
// // //     "city": "Raanana",
// // //     "distanceKm": 28.8,
// // //     "availableNow": false,
// // //     "reviews": 160,
// // //     "avatar": "/avatars/avatar10.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p20",
// // //     "name": "פרופסי 20",
// // //     "category": "Coaches and Veterinarians",
// // //     "rating": 4.63,
// // //     "pricePerHour": 400,
// // //     "city": "Beer Sheva",
// // //     "distanceKm": 14.1,
// // //     "availableNow": false,
// // //     "reviews": 154,
// // //     "avatar": "/avatars/avatar1.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p21",
// // //     "name": "Pro 21",
// // //     "category": "Construction, Crafts, and Industry",
// // //     "rating": 3.68,
// // //     "pricePerHour": 250,
// // //     "city": "Tel Aviv",
// // //     "distanceKm": 48.0,
// // //     "availableNow": false,
// // //     "reviews": 1,
// // //     "avatar": "/avatars/avatar2.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p22",
// // //     "name": "פרופסי 22",
// // //     "category": "Cleaning and Maintenance",
// // //     "rating": 3.61,
// // //     "pricePerHour": 400,
// // //     "city": "Haifa",
// // //     "distanceKm": 3.3,
// // //     "availableNow": false,
// // //     "reviews": 52,
// // //     "avatar": "/avatars/avatar3.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p23",
// // //     "name": "Pro 23",
// // //     "category": "Services, Hospitality, and Sales",
// // //     "rating": 4.53,
// // //     "pricePerHour": 400,
// // //     "city": "Jerusalem",
// // //     "distanceKm": 35.5,
// // //     "availableNow": false,
// // //     "reviews": 191,
// // //     "avatar": "/avatars/avatar4.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p24",
// // //     "name": "פרופסי 24",
// // //     "category": "Construction, Crafts, and Industry",
// // //     "rating": 4.88,
// // //     "pricePerHour": 400,
// // //     "city": "Haifa",
// // //     "distanceKm": 25.6,
// // //     "availableNow": false,
// // //     "reviews": 234,
// // //     "avatar": "/avatars/avatar5.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p25",
// // //     "name": "Pro 25",
// // //     "category": "Construction, Crafts, and Industry",
// // //     "rating": 4.88,
// // //     "pricePerHour": 80,
// // //     "city": "Raanana",
// // //     "distanceKm": 37.0,
// // //     "availableNow": false,
// // //     "reviews": 30,
// // //     "avatar": "/avatars/avatar6.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p26",
// // //     "name": "פרופסי 26",
// // //     "category": "Construction, Crafts, and Industry",
// // //     "rating": 3.81,
// // //     "pricePerHour": 150,
// // //     "city": "Jerusalem",
// // //     "distanceKm": 32.8,
// // //     "availableNow": true,
// // //     "reviews": 238,
// // //     "avatar": "/avatars/avatar7.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p27",
// // //     "name": "Pro 27",
// // //     "category": "Construction, Crafts, and Industry",
// // //     "rating": 4.5,
// // //     "pricePerHour": 400,
// // //     "city": "Haifa",
// // //     "distanceKm": 31.3,
// // //     "availableNow": false,
// // //     "reviews": 77,
// // //     "avatar": "/avatars/avatar8.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p28",
// // //     "name": "פרופסי 28",
// // //     "category": "Cleaning and Maintenance",
// // //     "rating": 4.77,
// // //     "pricePerHour": 300,
// // //     "city": "Haifa",
// // //     "distanceKm": 39.0,
// // //     "availableNow": true,
// // //     "reviews": 225,
// // //     "avatar": "/avatars/avatar9.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p29",
// // //     "name": "Pro 29",
// // //     "category": "Law, Finance, and Management",
// // //     "rating": 4.47,
// // //     "pricePerHour": 200,
// // //     "city": "Jerusalem",
// // //     "distanceKm": 46.2,
// // //     "availableNow": false,
// // //     "reviews": 226,
// // //     "avatar": "/avatars/avatar10.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   },
// // //   {
// // //     "id": "p30",
// // //     "name": "פרופסי 30",
// // //     "category": "Services, Hospitality, and Sales",
// // //     "rating": 4.95,
// // //     "pricePerHour": 400,
// // //     "city": "Beer Sheva",
// // //     "distanceKm": 8.7,
// // //     "availableNow": false,
// // //     "reviews": 152,
// // //     "avatar": "/avatars/avatar1.svg",
// // //     "bio": "מומחה עם ניסיון רב. זמין להדרכה ושירות."
// // //   }
// // // ];

// // // export const STORIES = [
// // //   {
// // //     "id": "s1",
// // //     "proId": "p1",
// // //     "title": "שיעור ניסיון חינם",
// // //     "img": "https://images.unsplash.com/photo-1502292566265-6b9c3a0f1a1e?w=1200&q=80&auto=format&fit=crop",
// // //     "short": "שיעור ניסיון לזמן מוגבל"
// // //   },
// // //   {
// // //     "id": "s2",
// // //     "proId": "p2",
// // //     "title": "ייעוץ עסקי מהיר",
// // //     "img": "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=1200&q=80&auto=format&fit=crop",
// // //     "short": "פגישת ייעוץ ראשונית"
// // //   },
// // //   {
// // //     "id": "s3",
// // //     "proId": "p13",
// // //     "title": "סיפור 3",
// // //     "img": "https://images.unsplash.com/photo-1599566150163-29194dcaad36?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&fm=jpg&q=60&w=3000",
// // //     "short": "הצעה מיוחדת לזמן מוגבל"
// // //   },
// // //   {
// // //     "id": "s4",
// // //     "proId": "p19",
// // //     "title": "סיפור 4",
// // //     "img": "/stories/story4.svg",
// // //     "short": "הצעה מיוחדת לזמן מוגבל"
// // //   },
// // //   {
// // //     "id": "s5",
// // //     "proId": "p16",
// // //     "title": "סיפור 5",
// // //     "img": "/stories/story5.svg",
// // //     "short": "הצעה מיוחדת לזמן מוגבל"
// // //   },
// // //   {
// // //     "id": "s6",
// // //     "proId": "p28",
// // //     "title": "סיפור 6",
// // //     "img": "/stories/story6.svg",
// // //     "short": "הצעה מיוחדת לזמן מוגבל"
// // //   }
// // // ];











// // export const PROFESSIONALS = [
// //   {
// //     "id": "p1",
// //     "name": "אילן כהן",
// //     "category": "מדריכים ומורים פרטיים",
// //     "rating": 4.9,
// //     "pricePerHour": 150,
// //     "city": "תל אביב - Tel Aviv",
// //     "distanceKm": 2.1,
// //     "availableNow": true,
// //     "reviews": 112,
// //     "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80&auto=format&fit=crop",
// //     "bio": "מורה פרטי למתמטיקה עם ניסיון של 10 שנים, מתמחה בהכנה לבגרויות ופסיכומטרי. גישה פרטנית ומותאמת אישית."
// //   },
// //   {
// //     "id": "p2",
// //     "name": "שרה גולדברג",
// //     "category": "משפט, פיננסים ומנהל",
// //     "rating": 4.7,
// //     "pricePerHour": 300,
// //     "city": "ירושלים - Jerusalem",
// //     "distanceKm": 48,
// //     "availableNow": false,
// //     "reviews": 45,
// //     "avatar": "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=800&q=80&auto=format&fit=crop",
// //     "bio": "עורכת דין מומחית לדיני עסקים, מעניקה ייעוץ משפטי לעסקים קטנים ובינוניים."
// //   },
// //   {
// //     "id": "p3",
// //     "name": "דוד לוי",
// //     "category": "מאמנים וטרינרים",
// //     "rating": 4.06,
// //     "pricePerHour": 80,
// //     "city": "נתניה - Netanya",
// //     "distanceKm": 46.4,
// //     "availableNow": false,
// //     "reviews": 48,
// //     "avatar": "https://images.unsplash.com/photo-1552058544-f2b08422138a?w=800&q=80&auto=format&fit=crop",
// //     "bio": "וטרינר מנוסה עם התמחות בחיות מחמד. מעניק טיפול מסור ואכפתי."
// //   },
// //   {
// //     "id": "p4",
// //     "name": "מיכל אברהם",
// //     "category": "שירותים, אירוח ומכירות",
// //     "rating": 4.62,
// //     "pricePerHour": 120,
// //     "city": "נתניה - Netanya",
// //     "distanceKm": 42.0,
// //     "availableNow": false,
// //     "reviews": 136,
// //     "avatar": "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=800&q=80&auto=format&fit=crop",
// //     "bio": "יועצת מכירות ושירות עם ניסיון של 8 שנים, מתמחה בחוויית לקוח מיטבית."
// //   },
// //   {
// //     "id": "p5",
// //     "name": "רון שטרית",
// //     "category": "משפט, פיננסים ומנהל",
// //     "rating": 3.85,
// //     "pricePerHour": 400,
// //     "city": "נתניה - Netanya",
// //     "distanceKm": 8.6,
// //     "availableNow": true,
// //     "reviews": 158,
// //     "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&q=80&auto=format&fit=crop",
// //     "bio": "יועץ פיננסי בכיר, מומחה לתכנון פנסיוני וניהול השקעות."
// //   },
// //   {
// //     "id": "p6",
// //     "name": "יעל מזרחי",
// //     "category": "ניקיון ותחזוקה",
// //     "rating": 4.71,
// //     "pricePerHour": 250,
// //     "city": "תל אביב - Tel Aviv",
// //     "distanceKm": 12.1,
// //     "availableNow": true,
// //     "reviews": 47,
// //     "avatar": "https://images.unsplash.com/photo-1581044777550-4cfa60707c03?w=800&q=80&auto=format&fit=crop",
// //     "bio": "אשת ניקיון מקצועית עם ניסיון בניקיון בתים ומשרדים. אמינה ומדויקת."
// //   },
// //   {
// //     "id": "p7",
// //     "name": "איתי פרץ",
// //     "category": "משפט, פיננסים ומנהל",
// //     "rating": 3.73,
// //     "pricePerHour": 250,
// //     "city": "נתניה - Netanya",
// //     "distanceKm": 34.2,
// //     "availableNow": false,
// //     "reviews": 111,
// //     "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80&auto=format&fit=crop",
// //     "bio": "רואה חשבון מוסמך, מתמחה בביקורת וניהול ספרים לעסקים."
// //   },
// //   {
// //     "id": "p8",
// //     "name": "שלמה כץ",
// //     "category": "בנייה, מלאכה ותעשייה",
// //     "rating": 4.52,
// //     "pricePerHour": 250,
// //     "city": "חיפה - Haifa",
// //     "distanceKm": 10.0,
// //     "availableNow": false,
// //     "reviews": 63,
// //     "avatar": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80&auto=format&fit=crop",
// //     "bio": "אינסטלטור מומחה עם 15 שנות ניסיון, מתקן כל תקלה במהירות ומקצועיות."
// //   },
// //   {
// //     "id": "p9",
// //     "name": "נעמה שפירא",
// //     "category": "מדריכים ומורים פרטיים",
// //     "rating": 3.64,
// //     "pricePerHour": 300,
// //     "city": "ירושלים - Jerusalem",
// //     "distanceKm": 33.4,
// //     "availableNow": false,
// //     "reviews": 146,
// //     "avatar": "https://images.unsplash.com/photo-1536922246289-88c42f957773?w=800&q=80&auto=format&fit=crop",
// //     "bio": "מורה פרטית לאנגלית, מתמחה בהכנה למבחנים ובשיפור יכולות שיחה."
// //   },
// //   {
// //     "id": "p10",
// //     "name": "ליאור דוד",
// //     "category": "שירותים, אירוח ומכירות",
// //     "rating": 4.86,
// //     "pricePerHour": 120,
// //     "city": "נתניה - Netanya",
// //     "distanceKm": 28.9,
// //     "availableNow": false,
// //     "reviews": 94,
// //     "avatar": "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&q=80&auto=format&fit=crop",
// //     "bio": "מנהל אירועים מקצועי, מתכנן ומנהל אירועים עסקיים ופרטיים."
// //   },
// //   {
// //     "id": "p11",
// //     "name": "עידן חן",
// //     "category": "בנייה, מלאכה ותעשייה",
// //     "rating": 4.85,
// //     "pricePerHour": 150,
// //     "city": "רעננה - Raanana",
// //     "distanceKm": 45.3,
// //     "availableNow": false,
// //     "reviews": 85,
// //     "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80&auto=format&fit=crop",
// //     "bio": "חשמלאי מוסמך, מתקן ומתקין מערכות חשמל ביתיות ותעשייתיות."
// //   },
// //   {
// //     "id": "p12",
// //     "name": "רותם ישראלי",
// //     "category": "בנייה, מלאכה ותעשייה",
// //     "rating": 4.87,
// //     "pricePerHour": 200,
// //     "city": "תל אביב - Tel Aviv",
// //     "distanceKm": 44.2,
// //     "availableNow": false,
// //     "reviews": 222,
// //     "avatar": "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=800&q=80&auto=format&fit=crop",
// //     "bio": "נגר אמנותי, מייצר רהיטים מותאמים אישית ועושה עבודות שיפוץ מעץ."
// //   },
// //   {
// //     "id": "p13",
// //     "name": "מיכאל גולן",
// //     "category": "משפט, פיננסים ומנהל",
// //     "rating": 3.96,
// //     "pricePerHour": 300,
// //     "city": "תל אביב - Tel Aviv",
// //     "distanceKm": 37.1,
// //     "availableNow": false,
// //     "reviews": 203,
// //     "avatar": "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800&q=80&auto=format&fit=crop",
// //     "bio": "יועץ עסקי אסטרטגי, מסייע לעסקים בצמיחה ובפיתוח תוכניות עבודה."
// //   },
// //   {
// //     "id": "p14",
// //     "name": "טל בר",
// //     "category": "מדריכים ומורים פרטיים",
// //     "rating": 4.63,
// //     "pricePerHour": 120,
// //     "city": "תל אביב - Tel Aviv",
// //     "distanceKm": 31.7,
// //     "availableNow": false,
// //     "reviews": 153,
// //     "avatar": "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=800&q=80&auto=format&fit=crop",
// //     "bio": "מורה פרטי לפיזיקה, מסביר מושגים מורכבים בצורה פשוטה וברורה."
// //   },
// //   {
// //     "id": "p15",
// //     "name": "אלעד מור",
// //     "category": "מאמנים וטרינרים",
// //     "rating": 4.18,
// //     "pricePerHour": 300,
// //     "city": "רעננה - Raanana",
// //     "distanceKm": 23.2,
// //     "availableNow": false,
// //     "reviews": 206,
// //     "avatar": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80&auto=format&fit=crop",
// //     "bio": "מאמן כושר אישי, מתמחה באימונים פונקציונליים ושיקום פציעות."
// //   },
// //   {
// //     "id": "p16",
// //     "name": "דניאל שמיר",
// //     "category": "משפט, פיננסים ומנהל",
// //     "rating": 4.5,
// //     "pricePerHour": 300,
// //     "city": "תל אביב - Tel Aviv",
// //     "distanceKm": 10.7,
// //     "availableNow": false,
// //     "reviews": 203,
// //     "avatar": "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=800&q=80&auto=format&fit=crop",
// //     "bio": "יועץ משכנתאות בכיר, מסייע במציאת ההלוואה המתאימה ביותר."
// //   },
// //   {
// //     "id": "p17",
// //     "name": "קרן אדלר",
// //     "category": "ניקיון ותחזוקה",
// //     "rating": 3.94,
// //     "pricePerHour": 200,
// //     "city": "ירושלים - Jerusalem",
// //     "distanceKm": 3.8,
// //     "availableNow": false,
// //     "reviews": 131,
// //     "avatar": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&q=80&auto=format&fit=crop",
// //     "bio": "מנקה חלונות מקצועית, מבצעת עבודות ניקיון בגובה ובמקומות מורכבים."
// //   },
// //   {
// //     "id": "p18",
// //     "name": "ירדן פלד",
// //     "category": "ניקיון ותחזוקה",
// //     "rating": 3.72,
// //     "pricePerHour": 300,
// //     "city": "חיפה - Haifa",
// //     "distanceKm": 0.6,
// //     "availableNow": false,
// //     "reviews": 5,
// //     "avatar": "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=800&q=80&auto=format&fit=crop",
// //     "bio": "אשת אחזקה כללית, מתקנת ומתחזקת מערכות ביתיות שונות."
// //   },
// //   {
// //     "id": "p19",
// //     "name": "גיל סגל",
// //     "category": "שירותים, אירוח ומכירות",
// //     "rating": 4.65,
// //     "pricePerHour": 200,
// //     "city": "רעננה - Raanana",
// //     "distanceKm": 28.8,
// //     "availableNow": false,
// //     "reviews": 160,
// //     "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80&auto=format&fit=crop",
// //     "bio": "סוכן נדל\"ן מנוסה, מתמחה במכירה והשכרת נכסים במרכז הארץ."
// //   },
// //   {
// //     "id": "p20",
// //     "name": "נועה הררי",
// //     "category": "מאמנים וטרינרים",
// //     "rating": 4.63,
// //     "pricePerHour": 400,
// //     "city": "באר שבע - Beer Sheva",
// //     "distanceKm": 14.1,
// //     "availableNow": false,
// //     "reviews": 154,
// //     "avatar": "https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=800&q=80&auto=format&fit=crop",
// //     "bio": "וטרינרית כירורגית, מתמחה בניתוחים מורכבים ורפואה דחופה."
// //   },
// //   {
// //     "id": "p21",
// //     "name": "אריאל בן דוד",
// //     "category": "בנייה, מלאכה ותעשייה",
// //     "rating": 3.68,
// //     "pricePerHour": 250,
// //     "city": "תל אביב - Tel Aviv",
// //     "distanceKm": 48.0,
// //     "availableNow": false,
// //     "reviews": 1,
// //     "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80&auto=format&fit=crop",
// //     "bio": "שיפוצניק כללי, מבצע עבודות שיפוץ קטנות וגדולות באיכות גבוהה."
// //   },
// //   {
// //     "id": "p22",
// //     "name": "מורן זיו",
// //     "category": "ניקיון ותחזוקה",
// //     "rating": 3.61,
// //     "pricePerHour": 400,
// //     "city": "חיפה - Haifa",
// //     "distanceKm": 3.3,
// //     "availableNow": false,
// //     "reviews": 52,
// //     "avatar": "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=800&q=80&auto=format&fit=crop",
// //     "bio": "מנהלת ניקיון למשרדים וחברות, מספקת שירותי ניקיון שוטף ועמוק."
// //   },
// //   {
// //     "id": "p23",
// //     "name": "אביב אשכנזי",
// //     "category": "שירותים, אירוח ומכירות",
// //     "rating": 4.53,
// //     "pricePerHour": 400,
// //     "city": "ירושלים - Jerusalem",
// //     "distanceKm": 35.5,
// //     "availableNow": false,
// //     "reviews": 191,
// //     "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80&auto=format&fit=crop",
// //     "bio": "מארגן חתונות ואירועים, מתכנן כל פרט לשביעות רצון מלאה."
// //   },
// //   {
// //     "id": "p24",
// //     "name": "רעות מלכה",
// //     "category": "בנייה, מלאכה ותעשייה",
// //     "rating": 4.88,
// //     "pricePerHour": 400,
// //     "city": "חיפה - Haifa",
// //     "distanceKm": 25.6,
// //     "availableNow": false,
// //     "reviews": 234,
// //     "avatar": "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=800&q=80&auto=format&fit=crop",
// //     "bio": "מעצבת פנים, יוצרת חללים פונקציונליים ואסתטיים בהתאם לצרכי הלקוח."
// //   },
// //   {
// //     "id": "p25",
// //     "name": "איתי דהן",
// //     "category": "בנייה, מלאכה ותעשייה",
// //     "rating": 4.88,
// //     "pricePerHour": 80,
// //     "city": "רעננה - Raanana",
// //     "distanceKm": 37.0,
// //     "availableNow": false,
// //     "reviews": 30,
// //     "avatar": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80&auto=format&fit=crop",
// //     "bio": "טכנאי גז מוסמך, מתקן ומתקין מערכות גז ביתיות ותעשייתיות."
// //   },
// //   {
// //     "id": "p26",
// //     "name": "ליאל כספי",
// //     "category": "בנייה, מלאכה ותעשייה",
// //     "rating": 3.81,
// //     "pricePerHour": 150,
// //     "city": "ירושלים - Jerusalem",
// //     "distanceKm": 32.8,
// //     "availableNow": true,
// //     "reviews": 238,
// //     "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80&auto=format&fit=crop",
// //     "bio": "צבע מקצועי, מבצע עבודות צביעה איכותיות בטכניקות מתקדמות."
// //   },
// //   {
// //     "id": "p27",
// //     "name": "עומר שחר",
// //     "category": "בנייה, מלאכה ותעשייה",
// //     "rating": 4.5,
// //     "pricePerHour": 400,
// //     "city": "חיפה - Haifa",
// //     "distanceKm": 31.3,
// //     "availableNow": false,
// //     "reviews": 77,
// //     "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80&auto=format&fit=crop",
// //     "bio": "מהנדס בניין, מפקח על עבודות בנייה ומספק ייעוץ הנדסי."
// //   },
// //   {
// //     "id": "p28",
// //     "name": "שירה ליברמן",
// //     "category": "ניקיון ותחזוקה",
// //     "rating": 4.77,
// //     "pricePerHour": 300,
// //     "city": "חיפה - Haifa",
// //     "distanceKm": 39.0,
// //     "availableNow": true,
// //     "reviews": 225,
// //     "avatar": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&q=80&auto=format&fit=crop",
// //     "bio": "מנקה בתים מקצועית, משתמשת בחומרים אקולוגיים וטכניקות ניקוי מתקדמות."
// //   },
// //   {
// //     "id": "p29",
// //     "name": "יניב פלדמן",
// //     "category": "משפט, פיננסים ומנהל",
// //     "rating": 4.47,
// //     "pricePerHour": 200,
// //     "city": "ירושלים - Jerusalem",
// //     "distanceKm": 46.2,
// //     "availableNow": false,
// //     "reviews": 226,
// //     "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&q=80&auto=format&fit=crop",
// //     "bio": "יועץ מס בכיר, מסייע בתכנון מס ובהתמודדות עם רשויות המס."
// //   },
// //   {
// //     "id": "p30",
// //     "name": "מאיה גבאי",
// //     "category": "שירותים, אירוח ומכירות",
// //     "rating": 4.95,
// //     "pricePerHour": 400,
// //     "city": "באר שבע - Beer Sheva",
// //     "distanceKm": 8.7,
// //     "availableNow": false,
// //     "reviews": 152,
// //     "avatar": "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=800&q=80&auto=format&fit=crop",
// //     "bio": "מנהלת משרד וירטואלית, מספקת שירותי אדמיניסטרציה ומזכירות לעסקים."
// //   }
// // ];

// // export const STORIES = [
// //   {
// //     "id": "s1",
// //     "proId": "p1",
// //     "title": "שיעור ניסיון חינם",
// //     "img": "https://images.unsplash.com/photo-1502292566265-6b9c3a0f1a1e?w=1200&q=80&auto=format&fit=crop",
// //     "short": "שיעור ניסיון לזמן מוגבל"
// //   },
// //   {
// //     "id": "s2",
// //     "proId": "p2",
// //     "title": "ייעוץ עסקי מהיר",
// //     "img": "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=1200&q=80&auto=format&fit=crop",
// //     "short": "פגישת ייעוץ ראשונית"
// //   },
// //   {
// //     "id": "s3",
// //     "proId": "p13",
// //     "title": "ייעוץ עסקי ללא התחייבות",
// //     "img": "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&q=80&auto=format&fit=crop",
// //     "short": "פגישת היכרות חינם"
// //   },
// //   {
// //     "id": "s4",
// //     "proId": "p19",
// //     "title": "הצעת נדל\"ן בלעדית",
// //     "img": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=80&auto=format&fit=crop",
// //     "short": "נכסים בהנחה לזמן מוגבל"
// //   },
// //   {
// //     "id": "s5",
// //     "proId": "p16",
// //     "title": "ייעוץ משכנתאות חינם",
// //     "img": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=80&auto=format&fit=crop",
// //     "short": "בדיקת זכאות ללא עלות"
// //   },
// //   {
// //     "id": "s6",
// //     "proId": "p28",
// //     "title": "ניקיון אביב בהנחה",
// //     "img": "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200&q=80&auto=format&fit=crop",
// //     "short": "הנחה של 20% לניקיון עמוק"
// //   }
// // ];













// export const PROFESSIONALS = [
//   {
//     id: "p1",
//     name: "אילן כהן",
//     category: "מדריכים ומורים פרטיים",
//     rating: 4.9,
//     pricePerHour: 150,
//     city: "תל אביב",
//     distanceKm: 2.1,
//     availableNow: true,
//     reviews: 112,
//     avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80&auto=format&fit=crop",
//     bio: "מורה פרטי למתמטיקה עם ניסיון של 10 שנים, מתמחה בהכנה לבגרויות ובהעלאת הישגים."
//   },
//   {
//     id: "p2",
//     name: "שרה גולדברג",
//     category: "משפט, פיננסים ומנהל",
//     rating: 4.7,
//     pricePerHour: 300,
//     city: "ירושלים",
//     distanceKm: 48,
//     availableNow: false,
//     reviews: 45,
//     avatar: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=800&q=80&auto=format&fit=crop",
//     bio: "עו״ד ייעוץ לעסקים קטנים – מספק מענה אסטרטגי, הסכמים וחוזים בשפה ברורה."
//   },
//   {
//     id: "p3",
//     name: "רועי לב",
//     category: "מאמנים וטרינרים",
//     rating: 4.06,
//     pricePerHour: 80,
//     city: "נתניה",
//     distanceKm: 46.4,
//     availableNow: false,
//     reviews: 48,
//     avatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&fm=jpg&q=60&w=3000",
//     bio: "מאמן כושר אישי עם ניסיון רב, מלווה לקוחות להשגת מטרות בריאות וכושר."
//   },
//   {
//     id: "p4",
//     name: "דורית פרן",
//     category: "שירותים, אירוח ומכירות",
//     rating: 4.62,
//     pricePerHour: 120,
//     city: "נתניה",
//     distanceKm: 42.0,
//     availableNow: false,
//     reviews: 136,
//     avatar: "https://images.unsplash.com/photo-1502767089025-6572583495b0?w=800&q=80&auto=format&fit=crop",
//     bio: "מנחת שירות ומכירות עם רקע בהדרכת צוותים בחברות אירוח – מדגישה חוויית לקוח."
//   },
//   {
//     id: "p5",
//     name: "מיכאל (מייק) סגל",
//     category: "משפט, פיננסים ומנהל",
//     rating: 3.85,
//     pricePerHour: 400,
//     city: "נתניה",
//     distanceKm: 8.6,
//     availableNow: true,
//     reviews: 158,
//     avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&q=80&auto=format&fit=crop",
//     bio: "יועץ פיננסי מוסמך – מתמחה בניהול תקציב אישי והשקעות למתחילים."
//   },
//   {
//     id: "p6",
//     name: "אביטל רוזן",
//     category: "ניקיון ותחזוקה",
//     rating: 4.71,
//     pricePerHour: 250,
//     city: "תל אביב",
//     distanceKm: 12.1,
//     availableNow: true,
//     reviews: 47,
//     avatar: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80&auto=format&fit=crop",
//     bio: "מנקה מקצועית מוסמכת – דגש על ניקיון יסודי, סביבת עבודה נקייה ובריאה."
//   },
//   {
//     id: "p7",
//     name: "דוד ברק",
//     category: "משפט, פיננסים ומנהל",
//     rating: 3.73,
//     pricePerHour: 250,
//     city: "נתניה",
//     distanceKm: 34.2,
//     availableNow: false,
//     reviews: 111,
//     avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80&auto=format&fit=crop",
//     bio: "מנהל פרויקטים עם ניסיון בחברות סטארט-אפ – מתמחה בהובלת צוותים וביצוע יעיל."
//   },
//   {
//     id: "p8",
//     name: "יעקב כהן",
//     category: "בנייה, מלאכה ותעשייה",
//     rating: 4.52,
//     pricePerHour: 250,
//     city: "חיפה",
//     distanceKm: 10.0,
//     availableNow: false,
//     reviews: 63,
//     avatar: "https://images.unsplash.com/photo-1542371772-419ccd12b28f?w=800&q=80&auto=format&fit=crop",
//     bio: "קבלן שיפוצים עם ניסיון בבתים פרטיים – יסודי, מקצועי, עומד בזמנים."
//   },
//   {
//     id: "p9",
//     name: "אורנה לוי",
//     category: "מדריכים ומורים פרטיים",
//     rating: 3.64,
//     pricePerHour: 300,
//     city: "ירושלים",
//     distanceKm: 33.4,
//     availableNow: false,
//     reviews: 146,
//     avatar: "https://images.unsplash.com/photo-1555529771-2452a384a501?w=800&q=80&auto=format&fit=crop",
//     bio: "מורה לאנגלית עם ניסיון בהכנה לבחינות חוץ-ארציות ולשיפור שיחה."
//   },
//   {
//     id: "p10",
//     name: "הילה סורוקה",
//     category: "שירותים, אירוח ומכירות",
//     rating: 4.86,
//     pricePerHour: 120,
//     city: "נתניה",
//     distanceKm: 28.9,
//     availableNow: false,
//     reviews: 94,
//     avatar: "https://images.unsplash.com/photo-1506086679526-3c42ce5f7256?w=800&q=80&auto=format&fit=crop",
//     bio: "יועצת מכירות ושירותים – מסייעת לעסקים קטנים לבנות מערך שירות לקוחות מנצח."
//   },
//   {
//     id: "p11",
//     name: "גלעד ישראלי",
//     category: "בנייה, מלאכה ותעשייה",
//     rating: 4.85,
//     pricePerHour: 150,
//     city: "רעננה",
//     distanceKm: 45.3,
//     availableNow: false,
//     reviews: 85,
//     avatar: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80&auto=format&fit=crop",
//     bio: "מכונאי תחזוקה ותעשייה עם ניסיון רב – פתרונות מקצועיים למפעלים ולבתי עסק."
//   },
//   {
//     id: "p12",
//     name: "נעה בן־דוד",
//     category: "בנייה, מלאכה ותעשייה",
//     rating: 4.87,
//     pricePerHour: 200,
//     city: "תל אביב",
//     distanceKm: 44.2,
//     availableNow: false,
//     reviews: 222,
//     avatar: "https://images.unsplash.com/photo-1519985176271-adb1088fa94c?w=800&q=80&auto=format&fit=crop",
//     bio: "טכנאית מערכות עם דגש על איכות, בטיחות והתאמה אישית."
//   },
//   {
//     id: "p13",
//     name: "איה כהן",
//     category: "משפט, פיננסים ומנהל",
//     rating: 3.96,
//     pricePerHour: 300,
//     city: "תל אביב",
//     distanceKm: 37.1,
//     availableNow: false,
//     reviews: 203,
//     avatar: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&q=80&auto=format&fit=crop",
//     bio: "יועצת משפטית פרטית – מספקת מענה לאנשים פרטיים בענייני ירושה, חוזים ומשפחה."
//   },
//   {
//     id: "p14",
//     name: "שלמה לוי",
//     category: "מדריכים ומורים פרטיים",
//     rating: 4.63,
//     pricePerHour: 120,
//     city: "תל אביב",
//     distanceKm: 31.7,
//     availableNow: false,
//     reviews: 153,
//     avatar: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&q=80&auto=format&fit=crop",
//     bio: "מורה לפיזיקה עם ניסיון בליווי אישי וציונים גבוהים."
//   },
//   {
//     id: "p15",
//     name: "אורית כהנא",
//     category: "מאמנים וטרינרים",
//     rating: 4.18,
//     pricePerHour: 300,
//     city: "רעננה",
//     distanceKm: 23.2,
//     availableNow: false,
//     reviews: 206,
//     avatar: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800&q=80&auto=format&fit=crop",
//     bio: "מאמנת כלבים מוסמכת – מסייעת לבניית ביטחון, משמעת וחברות עם חברכם הטוב."
//   },
//   {
//     id: "p16",
//     name: "רוני פרידמן",
//     category: "משפט, פיננסים ומנהל",
//     rating: 4.5,
//     pricePerHour: 300,
//     city: "תל אביב",
//     distanceKm: 10.7,
//     availableNow: false,
//     reviews: 203,
//     avatar: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80&auto=format&fit=crop",
//     bio: "יועצת מס עם התמחות בעסקים קטנים – עוזרת ליזמים להקים ולתפעל את החברה שלהם."
//   },
//   {
//     id: "p17",
//     name: "ערן גל",
//     category: "ניקיון ותחזוקה",
//     rating: 3.94,
//     pricePerHour: 200,
//     city: "ירושלים",
//     distanceKm: 3.8,
//     availableNow: false,
//     reviews: 131,
//     avatar: "https://images.unsplash.com/photo-1494891848038-9c38e7ed38f6?w=800&q=80&auto=format&fit=crop",
//     bio: "טכנאי מערכות תחזוקה – מענה מהיר לתקלות בבית ובעסק, שירות אמין."
//   },
//   {
//     id: "p18",
//     name: "מאיה כהן",
//     category: "ניקיון ותחזוקה",
//     rating: 3.72,
//     pricePerHour: 300,
//     city: "חיפה",
//     distanceKm: 0.6,
//     availableNow: false,
//     reviews: 5,
//     avatar: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80&auto=format&fit=crop",
//     bio: "עובדת ניקיון עם שירות לבתי פרטי; דגש על איכות וסביבת עבודה נעימה."
//   },
//   {
//     id: "p19",
//     name: "אורי סער",
//     category: "שירותים, אירוח ומכירות",
//     rating: 4.65,
//     pricePerHour: 200,
//     city: "רעננה",
//     distanceKm: 28.8,
//     availableNow: false,
//     reviews: 160,
//     avatar: "https://images.unsplash.com/photo-1536305030165-8f71a52f6d90?w=800&q=80&auto=format&fit=crop",
//     bio: "יועץ שירות עסקי – מלווה עסקים בתחילת הדרך ומדרבן צמיחה במכירות."
//   },
//   {
//     id: "p20",
//     name: "רועה ברק",
//     category: "מאמנים וטרינרים",
//     rating: 4.63,
//     pricePerHour: 400,
//     city: "באר שבע",
//     distanceKm: 14.1,
//     availableNow: false,
//     reviews: 154,
//     avatar: "https://images.unsplash.com/photo-1523473827532-7fdfa7d7049d?w=800&q=80&auto=format&fit=crop",
//     bio: "מאמן ספורט קבוצתי – מביא תוצאות לתרגילי כוח וסיבולת במתכונת אישית."
//   },
//   {
//     id: "p21",
//     name: "שרון דביר",
//     category: "בנייה, מלאכה ותעשייה",
//     rating: 3.68,
//     pricePerHour: 250,
//     city: "תל אביב",
//     distanceKm: 48.0,
//     availableNow: false,
//     reviews: 1,
//     avatar: "https://images.unsplash.com/photo-1522364723953-452d3431c267?w=800&q=80&auto=format&fit=crop",
//     bio: "פרילנסר בתחום טיאוף ועבודות קטנות – גמיש בהגעה וזמין לפרויקטים ביתיים."
//   },
//   {
//     id: "p22",
//     name: "הילה עצמון",
//     category: "ניקיון ותחזוקה",
//     rating: 3.61,
//     pricePerHour: 400,
//     city: "חיפה",
//     distanceKm: 3.3,
//     availableNow: false,
//     reviews: 52,
//     avatar: "https://images.unsplash.com/photo-1495567720989-cebdbdd97913?w=800&q=80&auto=format&fit=crop",
//     bio: "מנקה מוסמכת לעסקים – עובדת עם מערכות איכות וניהול סביבת עבודה נקייה."
//   },
//   {
//     id: "p23",
//     name: "מאור סופר",
//     category: "שירותים, אירוח ומכירות",
//     rating: 4.53,
//     pricePerHour: 400,
//     city: "ירושלים",
//     distanceKm: 35.5,
//     availableNow: false,
//     reviews: 191,
//     avatar: "https://images.unsplash.com/photo-1472417583565-62e7bdeda490?w=800&q=80&auto=format&fit=crop",
//     bio: "מומחה חוויית שירות – מארגן אירועים ומדריך צוותי מכירה בסניפים."
//   },
//   {
//     id: "p24",
//     name: "אלונה בבקוב",
//     category: "בנייה, מלאכה ותעשייה",
//     rating: 4.88,
//     pricePerHour: 400,
//     city: "חיפה",
//     distanceKm: 25.6,
//     availableNow: false,
//     reviews: 234,
//     avatar: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80&auto=format&fit=crop",
//     bio: "מנהלת עבודה באתרי בנייה – מקפידה על בטיחות, איכות ועבודה על פי תקן."
//   },
//   {
//     id: "p25",
//     name: "דניאל רבינוביץ׳",
//     category: "בנייה, מלאכה ותעשייה",
//     rating: 4.88,
//     pricePerHour: 80,
//     city: "רעננה",
//     distanceKm: 37.0,
//     availableNow: false,
//     reviews: 30,
//     avatar: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80&auto=format&fit=crop",
//     bio: "עוזר בנייה מוסמך – מציע עבודה איכותית במחיר נגיש."
//   },
//   {
//     id: "p26",
//     name: "שרית גולדשמידט",
//     category: "בנייה, מלאכה ותעשייה",
//     rating: 3.81,
//     pricePerHour: 150,
//     city: "ירושלים",
//     distanceKm: 32.8,
//     availableNow: true,
//     reviews: 238,
//     avatar: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=800&q=80&auto=format&fit=crop",
//     bio: "טכנאית מערכות בנייה – מתמקדת בפתרונות ידידותיים לסביבה ולתקציב."
//   },
//   {
//     id: "p27",
//     name: "אביתר מנור",
//     category: "בנייה, מלאכה ותעשייה",
//     rating: 4.5,
//     pricePerHour: 400,
//     city: "חיפה",
//     distanceKm: 31.3,
//     availableNow: false,
//     reviews: 77,
//     avatar: "https://images.unsplash.com/photo-1509228627150-4cea2e168eba?w=800&q=80&auto=format&fit=crop",
//     bio: "אינסטלטור מוסמך עם שירות באזור חיפה והצפון – מגיע במהירות."
//   },
//   {
//     id: "p28",
//     name: "נעמה לוי",
//     category: "ניקיון ותחזוקה",
//     rating: 4.77,
//     pricePerHour: 300,
//     city: "חיפה",
//     distanceKm: 39.0,
//     availableNow: true,
//     reviews: 225,
//     avatar: "https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=800&q=80&auto=format&fit=crop",
//     bio: "מנקה דירות מקצועית – דגש על פינוי יסודי, חיטוי ואביזרים איכותיים."
//   },
//   {
//     id: "p29",
//     name: "מירב חזן",
//     category: "משפט, פיננסים ומנהל",
//     rating: 4.47,
//     pricePerHour: 200,
//     city: "ירושלים",
//     distanceKm: 46.2,
//     availableNow: false,
//     reviews: 226,
//     avatar: "https://images.unsplash.com/photo-1524419062496-4b10257a872e?w=800&q=80&auto=format&fit=crop",
//     bio: "רו״ח מוסמכת – מעניקה ליווי חשבונאי וייעוץ מס לחברות קטנות ובעלי מקצוע."
//   },
//   {
//     id: "p30",
//     name: "גיל אורן",
//     category: "שירותים, אירוח ומכירות",
//     rating: 4.95,
//     pricePerHour: 400,
//     city: "באר שבע",
//     distanceKm: 8.7,
//     availableNow: false,
//     reviews: 152,
//     avatar: "https://images.unsplash.com/photo-1506967726955-3e0d3fb59d32?w=800&q=80&auto=format&fit=crop",
//     bio: "יועץ שירות ואירוח – מתמחה בהקמת מערכות שירות ודיגיטל לעסקים באזור הדרום."
//   }
// ];

// export const STORIES = [
//   {
//     id: "s1",
//     proId: "p1",
//     title: "שיעור ניסיון חינם",
//     img: "https://images.unsplash.com/photo-1502292566265-6b9c3a0f1a1e?w=1200&q=80&auto=format&fit=crop",
//     short: "שיעור ניסיון חינם לזמן מוגבל."
//   },
//   {
//     id: "s2",
//     proId: "p2",
//     title: "ייעוץ עסקי מהיר",
//     img: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=1200&q=80&auto=format&fit=crop",
//     short: "פגישת ייעוץ ראשונית במחיר מיוחד."
//   },
//   {
//     id: "s3",
//     proId: "p13",
//     title: "יועצת משפטית מומחית",
//     img: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&fm=jpg&q=60&w=3000",
//     short: "הצעה מיוחדת לשירות משפטי לזמן מוגבל."
//   },
//   {
//     id: "s4",
//     proId: "p19",
//     title: "צמיחה במכירות לעסקים",
//     img: "https://images.unsplash.com/photo-1536305030165-8f71a52f6d90?w=1200&q=80&auto=format&fit=crop",
//     short: "הצעה מיוחדת לייעוץ שירות ומכירות."
//   },
//   {
//     id: "s5",
//     proId: "p16",
//     title: "ייעוץ מס לעסקים קטנים",
//     img: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80&auto=format&fit=crop",
//     short: "פגישת ייעוץ מס במחיר כניסה."
//   },
//   {
//     id: "s6",
//     proId: "p28",
//     title: "הצעת ניקיון מוכחת",
//     img: "https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=1200&q=80&auto=format&fit=crop",
//     short: "ניקיון יסודי לדירות חדשות במחיר מיוחד."
//   }
// ];













//////Claude: 

export const PROFESSIONALS = [
  {
    "id": "p1",
    "name": "אילן כהן",
    "category": "מדריכים ומורים פרטיים",
    "categoryEn": "Tutors and Private Teachers",
    "rating": 4.9,
    "pricePerHour": 150,
    "city": "תל אביב",
    "cityEn": "Tel Aviv",
    "distanceKm": 2.1,
    "availableNow": true,
    "reviews": 112,
    "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80&auto=format&fit=crop",
    "bio": "מורה פרטי למתמטיקה ופיזיקה עם ניסיון של 10 שנים. מתמחה בהכנה לבגרויות ופסיכומטרי. גישה אישית וסבלנית לכל תלמיד."
  },
  {
    "id": "p2",
    "name": "שרה גולדברג",
    "category": "משפט, פיננסים ומנהל",
    "categoryEn": "Law, Finance, and Management",
    "rating": 4.7,
    "pricePerHour": 300,
    "city": "ירושלים",
    "cityEn": "Jerusalem",
    "distanceKm": 48,
    "availableNow": false,
    "reviews": 45,
    "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&q=80&auto=format&fit=crop",
    "bio": "עורכת דין מומחית במשפט מסחרי. מספקת ייעוץ משפטי לעסקים קטנים ובינוניים, ניהול משא ומתן וליווי עסקאות."
  },
  {
    "id": "p3",
    "name": "דוד מזרחי",
    "category": "מאמנים וטרינרים",
    "categoryEn": "Coaches and Veterinarians",
    "rating": 4.06,
    "pricePerHour": 80,
    "city": "נתניה",
    "cityEn": "Netanya",
    "distanceKm": 46.4,
    "availableNow": false,
    "reviews": 48,
    "avatar": "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=800&q=80&auto=format&fit=crop",
    "bio": "מאמן כושר אישי מוסמך. מתמחה באימוני כוח, אירובי ותזונה ספורטיבית. בונה תוכניות אימון מותאמות אישית."
  },
  {
    "id": "p4",
    "name": "מיכל לוי",
    "category": "שירותים, אירוח ומכירות",
    "categoryEn": "Services, Hospitality, and Sales",
    "rating": 4.62,
    "pricePerHour": 120,
    "city": "נתניה",
    "cityEn": "Netanya",
    "distanceKm": 42.0,
    "availableNow": false,
    "reviews": 136,
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80&auto=format&fit=crop",
    "bio": "מארגנת אירועים מקצועית. מתמחה בחתונות, אירועי חברה ובר/בת מצווה. שירות מלא מהתכנון ועד הביצוע."
  },
  {
    "id": "p5",
    "name": "יוסי אברהם",
    "category": "משפט, פיננסים ומנהל",
    "categoryEn": "Law, Finance, and Management",
    "rating": 3.85,
    "pricePerHour": 400,
    "city": "נתניה",
    "cityEn": "Netanya",
    "distanceKm": 8.6,
    "availableNow": true,
    "reviews": 158,
    "avatar": "https://images.unsplash.com/photo-1556157382-97eda2d62296?w=800&q=80&auto=format&fit=crop",
    "bio": "יועץ פיננסי בכיר. מתמחה בתכנון פיננסי אישי, ניהול השקעות ופנסיוני. עוזר ללקוחות להשיג יעדים פיננסיים ארוכי טווח."
  },
  {
    "id": "p6",
    "name": "רחל שפירא",
    "category": "ניקיון ותחזוקה",
    "categoryEn": "Cleaning and Maintenance",
    "rating": 4.71,
    "pricePerHour": 250,
    "city": "תל אביב",
    "cityEn": "Tel Aviv",
    "distanceKm": 12.1,
    "availableNow": true,
    "reviews": 47,
    "avatar": "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=800&q=80&auto=format&fit=crop",
    "bio": "מנהלת צוות ניקיון מקצועי. מתמחה בניקיון יסודי של דירות, משרדים ובתים פרטיים. עובדת עם חומרי ניקוי ידידותיים לסביבה."
  },
  {
    "id": "p7",
    "name": "עומר ביטון",
    "category": "משפט, פיננסים ומנהל",
    "categoryEn": "Law, Finance, and Management",
    "rating": 3.73,
    "pricePerHour": 250,
    "city": "נתניה",
    "cityEn": "Netanya",
    "distanceKm": 34.2,
    "availableNow": false,
    "reviews": 111,
    "avatar": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80&auto=format&fit=crop",
    "bio": "יועץ עסקי ואסטרטגי. מסייע לעסקים בפיתוח אסטרטגיות צמיחה, שיפור תהליכים ועלייה ברווחיות."
  },
  {
    "id": "p8",
    "name": "תמר אוחיון",
    "category": "בנייה, מלאכה ותעשייה",
    "categoryEn": "Construction, Crafts, and Industry",
    "rating": 4.52,
    "pricePerHour": 250,
    "city": "חיפה",
    "cityEn": "Haifa",
    "distanceKm": 10.0,
    "availableNow": false,
    "reviews": 63,
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80&auto=format&fit=crop",
    "bio": "אדריכלית פנים מנוסה. מתמחה בעיצוב ושיפוץ דירות ומשרדים. יוצרת מרחבים פונקציונליים ויפים עם תקציב מבוקר."
  },
  {
    "id": "p9",
    "name": "אבי כץ",
    "category": "מדריכים ומורים פרטיים",
    "categoryEn": "Tutors and Private Teachers",
    "rating": 3.64,
    "pricePerHour": 300,
    "city": "ירושלים",
    "cityEn": "Jerusalem",
    "distanceKm": 33.4,
    "availableNow": false,
    "reviews": 146,
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80&auto=format&fit=crop",
    "bio": "מורה פרטי לאנגלית וספרות. מתמחה בהכנה למבחני TOEFL ו-SAT. שיטות הוראה מתקדמות וממוקדות תוצאות."
  },
  {
    "id": "p10",
    "name": "נועה דהן",
    "category": "שירותים, אירוח ומכירות",
    "categoryEn": "Services, Hospitality, and Sales",
    "rating": 4.86,
    "pricePerHour": 120,
    "city": "נתניה",
    "cityEn": "Netanya",
    "distanceKm": 28.9,
    "availableNow": false,
    "reviews": 94,
    "avatar": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&q=80&auto=format&fit=crop",
    "bio": "סוכנת נדל״ן מובילה. מתמחה במכירה והשכרת דירות באזור המרכז. שירות אישי ומקצועי ללווי מלא בתהליך."
  },
  {
    "id": "p11",
    "name": "גיא רוזנברג",
    "category": "בנייה, מלאכה ותעשייה",
    "categoryEn": "Construction, Crafts, and Industry",
    "rating": 4.85,
    "pricePerHour": 150,
    "city": "רעננה",
    "cityEn": "Raanana",
    "distanceKm": 45.3,
    "availableNow": false,
    "reviews": 85,
    "avatar": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80&auto=format&fit=crop",
    "bio": "חשמלאי מוסמך עם 15 שנות ניסיון. מבצע עבודות חשמל ביתיות ותעשייתיות, טיפול בתקלות חשמל וחיווט חכם."
  },
  {
    "id": "p12",
    "name": "יעל ברזילי",
    "category": "בנייה, מלאכה ותעשייה",
    "categoryEn": "Construction, Crafts, and Industry",
    "rating": 4.87,
    "pricePerHour": 200,
    "city": "תל אביב",
    "cityEn": "Tel Aviv",
    "distanceKm": 44.2,
    "availableNow": false,
    "reviews": 222,
    "avatar": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&q=80&auto=format&fit=crop",
    "bio": "נגרת מקצועית. מתמחה בריהוט מעוצב על פי מידה, שיפוץ רהיטים עתיקים וארונות מטבח. עבודת יד איכותית ומדויקת."
  },
  {
    "id": "p13",
    "name": "אלון שמש",
    "category": "משפט, פיננסים ומנהל",
    "categoryEn": "Law, Finance, and Management",
    "rating": 3.96,
    "pricePerHour": 300,
    "city": "תל אביב",
    "cityEn": "Tel Aviv",
    "distanceKm": 37.1,
    "availableNow": false,
    "reviews": 203,
    "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&q=80&auto=format&fit=crop",
    "bio": "רואה חשבון מוסמך. מספק שירותי הנהלת חשבונות, דיווחי מס והתייעצות פיננסית לעסקים ויזמים."
  },
  {
    "id": "p14",
    "name": "שירה וקנין",
    "category": "מדריכים ומורים פרטיים",
    "categoryEn": "Tutors and Private Teachers",
    "rating": 4.63,
    "pricePerHour": 120,
    "city": "תל אביב",
    "cityEn": "Tel Aviv",
    "distanceKm": 31.7,
    "availableNow": false,
    "reviews": 153,
    "avatar": "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=800&q=80&auto=format&fit=crop",
    "bio": "מורה לפסנתר וקולנוע. מלמדת תלמידים מגיל 5 ומעלה, ממתחילים ועד מתקדמים. גישה מעוררת השראה וחיבור למוזיקה."
  },
  {
    "id": "p15",
    "name": "רון אשכנזי",
    "category": "מאמנים וטרינרים",
    "categoryEn": "Coaches and Veterinarians",
    "rating": 4.18,
    "pricePerHour": 300,
    "city": "רעננה",
    "cityEn": "Raanana",
    "distanceKm": 23.2,
    "availableNow": false,
    "reviews": 206,
    "avatar": "https://images.unsplash.com/photo-1552058544-f2b08422138a?w=800&q=80&auto=format&fit=crop",
    "bio": "וטרינר מוסמך. מטפל בחיות מחמד, חיסונים, טיפולי שיניים וניתוחים. מספק שירות מסור ואוהב חיות."
  },
  {
    "id": "p16",
    "name": "מאיה פרידמן",
    "category": "משפט, פיננסים ומנהל",
    "categoryEn": "Law, Finance, and Management",
    "rating": 4.5,
    "pricePerHour": 300,
    "city": "תל אביב",
    "cityEn": "Tel Aviv",
    "distanceKm": 10.7,
    "availableNow": false,
    "reviews": 203,
    "avatar": "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&q=80&auto=format&fit=crop",
    "bio": "יועצת משאבי אנוש. מסייעת לארגונים בגיוס, הכשרת עובדים ופיתוח תרבות ארגונית חיובית."
  },
  {
    "id": "p17",
    "name": "דני חדד",
    "category": "ניקיון ותחזוקה",
    "categoryEn": "Cleaning and Maintenance",
    "rating": 3.94,
    "pricePerHour": 200,
    "city": "ירושלים",
    "cityEn": "Jerusalem",
    "distanceKm": 3.8,
    "availableNow": false,
    "reviews": 131,
    "avatar": "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&q=80&auto=format&fit=crop",
    "bio": "מומחה לתחזוקת גינות. מספק שירותי גיזום, עיצוב נוף, השקיה אוטומטית וטיפול בדשא. גינה ירוקה ומטופחת כל השנה."
  },
  {
    "id": "p18",
    "name": "סיגל מנשה",
    "category": "ניקיון ותחזוקה",
    "categoryEn": "Cleaning and Maintenance",
    "rating": 3.72,
    "pricePerHour": 300,
    "city": "חיפה",
    "cityEn": "Haifa",
    "distanceKm": 0.6,
    "availableNow": false,
    "reviews": 5,
    "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80&auto=format&fit=crop",
    "bio": "מנקה מקצועית לאחר שיפוצים. מתמחה בניקיון יסודי של בתים ודירות לאחר עבודות בנייה. תוצאה מושלמת מובטחת."
  },
  {
    "id": "p19",
    "name": "אורי גבע",
    "category": "שירותים, אירוח ומכירות",
    "categoryEn": "Services, Hospitality, and Sales",
    "rating": 4.65,
    "pricePerHour": 200,
    "city": "רעננה",
    "cityEn": "Raanana",
    "distanceKm": 28.8,
    "availableNow": false,
    "reviews": 160,
    "avatar": "https://images.unsplash.com/photo-1463453091185-61582044d556?w=800&q=80&auto=format&fit=crop",
    "bio": "צלם מקצועי לאירועים. מתמחה בצילום חתונות, בר מצווה ואירועי חברה. לוכד רגעים בלתי נשכחים עם עין אמנותית."
  },
  {
    "id": "p20",
    "name": "רינת חיים",
    "category": "מאמנים וטרינרים",
    "categoryEn": "Coaches and Veterinarians",
    "rating": 4.63,
    "pricePerHour": 400,
    "city": "באר שבע",
    "cityEn": "Beer Sheva",
    "distanceKm": 14.1,
    "availableNow": false,
    "reviews": 154,
    "avatar": "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=800&q=80&auto=format&fit=crop",
    "bio": "מאמנת אישית להתפתחות אישית וקריירה. מסייעת בהגדרת יעדים, התמודדות עם אתגרים והשגת הצלחה אישית ומקצועית."
  },
  {
    "id": "p21",
    "name": "משה עזרא",
    "category": "בנייה, מלאכה ותעשייה",
    "categoryEn": "Construction, Crafts, and Industry",
    "rating": 3.68,
    "pricePerHour": 250,
    "city": "תל אביב",
    "cityEn": "Tel Aviv",
    "distanceKm": 48.0,
    "availableNow": false,
    "reviews": 1,
    "avatar": "https://images.unsplash.com/photo-1503443207922-dff7d543fd0e?w=800&q=80&auto=format&fit=crop",
    "bio": "שרברב מוסמך. מטפל בתקלות אינסטלציה, החלפת אביזרים ושיפוצי אמבטיות. זמין לשירות חירום 24/7."
  },
  {
    "id": "p22",
    "name": "לירון סלע",
    "category": "ניקיון ותחזוקה",
    "categoryEn": "Cleaning and Maintenance",
    "rating": 3.61,
    "pricePerHour": 400,
    "city": "חיפה",
    "cityEn": "Haifa",
    "distanceKm": 3.3,
    "availableNow": false,
    "reviews": 52,
    "avatar": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80&auto=format&fit=crop",
    "bio": "מנקה חלונות מקצועית. מתמחה בניקוי חלונות בבניינים גבוהים, חלונות פרגולות וקירות זכוכית. עבודה בטיחותית ויסודית."
  },
  {
    "id": "p23",
    "name": "יניב גולן",
    "category": "שירותים, אירוח ומכירות",
    "categoryEn": "Services, Hospitality, and Sales",
    "rating": 4.53,
    "pricePerHour": 400,
    "city": "ירושלים",
    "cityEn": "Jerusalem",
    "distanceKm": 35.5,
    "availableNow": false,
    "reviews": 191,
    "avatar": "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800&q=80&auto=format&fit=crop",
    "bio": "שף פרטי מנוסה. מכין ארוחות גורמה בבית הלקוח, ארוחות שבת ומסיבות. תפריטים מגוונים ומותאמים אישית."
  },
  {
    "id": "p24",
    "name": "שלומית אלון",
    "category": "בנייה, מלאכה ותעשייה",
    "categoryEn": "Construction, Crafts, and Industry",
    "rating": 4.88,
    "pricePerHour": 400,
    "city": "חיפה",
    "cityEn": "Haifa",
    "distanceKm": 25.6,
    "availableNow": false,
    "reviews": 234,
    "avatar": "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&q=80&auto=format&fit=crop",
    "bio": "מהנדסת בנייה בכירה. מנהלת פרויקטי בנייה מורכבים, משקמת מבנים ומפקחת על ביצוע לפי תקן. מקצועיות ודיוק."
  },
  {
    "id": "p25",
    "name": "בועז כהן",
    "category": "בנייה, מלאכה ותעשייה",
    "categoryEn": "Construction, Crafts, and Industry",
    "rating": 4.88,
    "pricePerHour": 80,
    "city": "רעננה",
    "cityEn": "Raanana",
    "distanceKm": 37.0,
    "availableNow": false,
    "reviews": 30,
    "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80&auto=format&fit=crop",
    "bio": "צבע ושפכטל מקצועי. מבצע עבודות גמר איכוותיות, צביעת דירות ושיקום קירות פגומים. תשומת לב לפרטים הקטנים."
  },
  {
    "id": "p26",
    "name": "אורנה דוידי",
    "category": "בנייה, מלאכה ותעשייה",
    "categoryEn": "Construction, Crafts, and Industry",
    "rating": 3.81,
    "pricePerHour": 150,
    "city": "ירושלים",
    "cityEn": "Jerusalem",
    "distanceKm": 32.8,
    "availableNow": true,
    "reviews": 238,
    "avatar": "https://images.unsplash.com/photo-1598550874175-4d0ef436c909?w=800&q=80&auto=format&fit=crop",
    "bio": "מעצבת גרפית ואמנית. מציירת ציורי קיר מרהיבים, מורלים ואומנות רחוב. הופכת קירות רגילים ליצירות אמנות."
  },
  {
    "id": "p27",
    "name": "איתי לביא",
    "category": "בנייה, מלאכה ותעשייה",
    "categoryEn": "Construction, Crafts, and Industry",
    "rating": 4.5,
    "pricePerHour": 400,
    "city": "חיפה",
    "cityEn": "Haifa",
    "distanceKm": 31.3,
    "availableNow": false,
    "reviews": 77,
    "avatar": "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=800&q=80&auto=format&fit=crop",
    "bio": "טכנאי מזגנים ומקררים. מבצע תחזוקה שוטפת, תיקונים ומכירת מזגנים חדשים. שירות מהיר ואמין."
  },
  {
    "id": "p28",
    "name": "חגית רון",
    "category": "ניקיון ותחזוקה",
    "categoryEn": "Cleaning and Maintenance",
    "rating": 4.77,
    "pricePerHour": 300,
    "city": "חיפה",
    "cityEn": "Haifa",
    "distanceKm": 39.0,
    "availableNow": true,
    "reviews": 225,
    "avatar": "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&q=80&auto=format&fit=crop",
    "bio": "מומחית ניקיון עמוק ואקולוגי. משתמשת במוצרים ידידותיים לסביבה ובטכניקות ניקוי חדשניות. בית נקי ובריא."
  },
  {
    "id": "p29",
    "name": "נדב ברק",
    "category": "משפט, פיננסים ומנהל",
    "categoryEn": "Law, Finance, and Management",
    "rating": 4.47,
    "pricePerHour": 200,
    "city": "ירושלים",
    "cityEn": "Jerusalem",
    "distanceKm": 46.2,
    "availableNow": false,
    "reviews": 226,
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80&auto=format&fit=crop",
    "bio": "יועץ כלכלי לעסקים קטנים. מסייע ביצירת תכניות עסקיות, מציאת מימון וניהול תזרים מזומנים יעיל."
  },
  {
    "id": "p30",
    "name": "הדר אבוטבול",
    "category": "שירותים, אירוח ומכירות",
    "categoryEn": "Services, Hospitality, and Sales",
    "rating": 4.95,
    "pricePerHour": 400,
    "city": "באר שבע",
    "cityEn": "Beer Sheva",
    "distanceKm": 8.7,
    "availableNow": false,
    "reviews": 152,
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80&auto=format&fit=crop",
    "bio": "מעצבת אירועים ומפיקה. יוצרת חוויות בלתי נשכחות עם עיצוב ייחודי, תאורה אומנותית וקונספט מדהים לכל אירוע."
  }
];

export const STORIES = [
  {
    "id": "s1",
    "proId": "p1",
    "title": "שיעור ניסיון חינם",
    "img": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&q=80&auto=format&fit=crop",
    "short": "שיעור ניסיון חינם למתמטיקה - זמן מוגבל!"
  },
  {
    "id": "s2",
    "proId": "p2",
    "title": "ייעוץ עסקי מהיר",
    "img": "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=80&auto=format&fit=crop",
    "short": "פגישת ייעוץ משפטי ראשונית במחיר מיוחד"
  },
  {
    "id": "s3",
    "proId": "p13",
    "title": "חודש ראשון חינם",
    "img": "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&q=80&auto=format&fit=crop",
    "short": "ניהול ספרים - החודש הראשון ללא עלות"
  },
  {
    "id": "s4",
    "proId": "p19",
    "title": "מבצע צילום חתונות",
    "img": "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=1200&q=80&auto=format&fit=crop",
    "short": "הזמינו עכשיו וקבלו אלבום דיגיטלי במתנה"
  },
  {
    "id": "s5",
    "proId": "p16",
    "title": "ייעוץ משאבי אנוש",
    "img": "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1200&q=80&auto=format&fit=crop",
    "short": "הערכת עובדים ראשונה במחיר מיוחד"
  },
  {
    "id": "s6",
    "proId": "p28",
    "title": "ניקיון אביב מיוחד",
    "img": "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200&q=80&auto=format&fit=crop",
    "short": "שירות ניקיון מקיף בהנחה של 20%"
  }
];